from enum import Enum


class TranscribeStatus(str, Enum):
    UPLOADED = "UPLOADED"
    TRANSCRIBING = "TRANSCRIBING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class FrameExtractionStatus(str, Enum):
    UPLOADED = "UPLOADED"
    EXTRACTING = "EXTRACTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class WorkflowState(str, Enum):
    DRAFT_GENERATING = "DRAFT_GENERATING"
    WAITING_USER_APPROVAL = "WAITING_USER_APPROVAL"
    FINAL_GENERATING = "FINAL_GENERATING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class DeletionStatus(str, Enum):
    NONE = "NONE"
    PENDING_DELETE = "PENDING_DELETE"
    DELETING = "DELETING"
    DELETE_FAILED = "DELETE_FAILED"
    PURGED = "PURGED"
